modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"

[[mods]]
modId="amrac"
version="${version}"
displayName="AMRAC"
authors="nonamenov6638, EmanonTheBeauty, uumatter, AntsHsu"
description='''Adds flyable combat aircraft with fixed-wing physics, radar, missiles, cannon, AI pilots and long-range BVR simulation.'''
iconFile="assets/amrac/icon.png"

[[mixins]]
config="amrac.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.amrac]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.amrac]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},26.3)"
ordering="NONE"
side="BOTH"
